kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: argo
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: kartiknaik/task-app-backend:v1
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/taskmanager"
        - name: JWT_SECRET
          value: ""
        readinessProbe:
          httpGet:
            path: /api
            port: 5000
            host: backend-service
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000