kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: argo
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: kartiknaik/note-app-backend:v2
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://root:root@mongo-service:27017/taskmanager?authSource=admin"
        - name: JWT_SECRET
          value: "your_jwt_secret_here"
        initContainers:
        - name: wait-for-mongodb
          image: busybox:1.28
          command: ['sh', '-c', 'until nc -z mongo-service 27017; do echo waiting for mongodb; sleep 2; done;']
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort