kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: argo
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: kartiknaik/task-app-backend:v4
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://root:root@mongo-service:27017/taskmanager?authSource=admin"
        - name: JWT_SECRET
          value: "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1NTY5ODU0MCwiaWF0IjoxNzU1Njk4NTQwfQ.dvYWq3zanTpztLAR4t3cKUZ_4dUciESEsujB89Q_VNs"

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: argo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000