apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: argo
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: kartiknaik/task-manager-frontend:v5
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://backend-service:5000/api"
        - name: SHELL
          value: /bin/bash
        - name: BROWSER
          value: none
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3

---


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: argo
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort




