kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchlabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: 
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/taskmanager"
        - name: JWT_SECRET
          value: ""


---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000