apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      initContainers:
      - name: init-container
        image: curlimages/curl:latest
        command: ['sh', '-c' , until curl -s  "http://backend-service:5000/api' && do echo "Initializing frontend..."; sleep 5; done']
      containers:
      - name: frontend-container
        image: kartiknaik/task-manager-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://backend-service:5000/api"


---


apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app:frontend
sepc:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort




