kind: Deployment
apiVersion: apps/v1
metadata:
  name: mongodb-deployment
  namespace: argo
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONOGO_USERNAME
          value: "root"
        - name: MONGO_PASSWORD
          value: "root"


---



kind: Service
apiVersion: v1
metadata:
  name: mongo-service
  namespace: argo
  labels:
    app: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
  type: NodePort