name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: cheackout

    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl --fail http://localhost:9000/api/system/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5


    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Wiat for the sonarqube to be ready
      run: |
        echo "Wiating for the sonarqube to be ready..."
        until curl -s http://localhost:9000/api/system/health | grep -q '"status":"GREEN"'; do
          echo "SonarQube is not ready yet. Waiting..."
          sleep 5
        done


    - name: SonarQube Scan
      run: |
        sonar-scanner \
          -Dsonar.projectKey=my_project \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=admin \
          -Dsonar.password=admin

  security-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL

