name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  sonarqube-analysis:
    runs-on: self-hosted
    needs: cheackout
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  security-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL

