name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  codeql-analysis:
    runs-on: ubuntu-latest
    needs: cheackout
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL 
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

    

  security-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL

