name: Node.js CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  # Stage 1: Checkout
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  # Stage 2: Code Quality
  code-quality:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v8.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Stage 3: Security Scan
  security-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@v0.9.1
        with:
          scan-type: fs
          format: table
          severity: CRITICAL

  # Stage 4: SonarQube Analysis
  sonar:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.0
        with:
          args: -X
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
