name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: set up node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: '18'
      # - name: Install dependencies
      #   run: npm install
  
  test:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:

      - name: Super-linter
        uses: super-linter/super-linter@v8.1.0 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_BRANCH: main

      - name: sonarqube scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL

