name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  codeql-analysis:
    runs-on: ubuntu-latest
    needs: cheackout
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Initialize CodeQL 
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: codeql-report.sarif
      
      - name: logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeql-logs
          path: codeql-report.sarif 

    

  trivy-file-system-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL
            output: trivy-report.sarif
            output-format: sarif
            ignore-unfixed: true
      - name: logs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-logs
          path: trivy-report.sarif



  docker-build:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Read the env 
        run: |
          echo "frontend-version=$(cat frontend/version.txt)" >> $GITHUB_ENV
          echo "the frontend version is $frontend-version"

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest
      #     cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/my-app:cache
      #     cache-to: type=inline