name: CI-pipeline

on:
  push:
    branches:
        - main
  
jobs:
  cheackout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master # Ex: v4.0.0, See the latest version at https://github.com/marketplace/actions/sonarcloud-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  security-scan:
    runs-on: ubuntu-latest
    needs: cheackout
    steps:
      - name: Trivy Vulnerability Scan  
        uses: aquasecurity/trivy-action@master
        with:
            scan-type: fs
            format: table
            severity: CRITICAL

